package org.data.functional;

import java.util.*;
import java.lang.reflect.Method;

/**
 * Demonstrates what type erasure means in practice.
 * Type erasure replaces generic type parameters with their bounds
 * (or {@link Object} if unbounded), removes generic metadata,
 * and inserts casts where needed.
 *
 * The methods in this class show the real‑world effects of erasure.
 */
public class TypeErasureDemo {

    /**
     * Proves that {@code List<String>} and {@code List<Integer>}
     * share the same runtime class.
     */
    public static boolean sameRuntimeClass() {
        List<String> strings = new ArrayList<>();
        List<Integer> integers = new ArrayList<>();
        return strings.getClass() == integers.getClass(); // true (both ArrayList)
    }

    /**
     * A raw {@code instanceof List} check is legal,
     * but {@code instanceof List<String>} is illegal at compile time.
     * This method shows the raw check that survives erasure.
     */
    public static boolean rawInstanceofCheck(Object obj) {
        return obj instanceof List; // legal
        // obj instanceof List<String>  // compilation error
    }

    /**
     * Heap pollution: putting an {@link Integer} into a {@code List<String>}
     * through a raw assignment. The compiler cannot stop it because the
     * generics are erased at runtime.
     *
     * @return the polluted list (contains an Integer)
     */
    @SuppressWarnings({"rawtypes", "unchecked"})
    public static List<String> heapPollutionExample() {
        List<String> strings = new ArrayList<>();
        List raw = strings;     // raw type – erasure turns both into List
        raw.add(42);            // compiles fine, no warning on raw
        return strings;         // now contains an Integer
    }

    /**
     * Generic array creation is illegal ({@code new T[10]}),
     * but you can create an {@code Object[]} and cast it.
     * This method returns an array of type {@code T} via the cast trick.
     * The cast is unchecked and produces a compiler warning.
     */
    @SuppressWarnings("unchecked")
    public static <T> T[] createGenericArray(int size) {
        // new T[size]  ← compilation error
        return (T[]) new Object[size]; // unchecked cast
    }

    /**
     * Shows that bridge methods are generated by the compiler
     * when a subclass overrides a method with a more specific parameter type.
     * The bridge method ensures polymorphism works after erasure.
     *
     * <p>We compare the methods of {@link DateNode} with those of its
     * parent {@link Node}.
     */
    public static void printBridgeMethods() {
        System.out.println("--- Node methods ---");
        for (Method m : Node.class.getDeclaredMethods()) {
            System.out.println(m);
        }
        System.out.println("--- DateNode methods ---");
        for (Method m : DateNode.class.getDeclaredMethods()) {
            System.out.println(m);
        }
        // The output includes a bridge method in DateNode:
        // setValue(Object)  (bridge)  and setValue(LocalDate)
    }

    // ------------------------------------------------------------
    // Helper types for bridge method demonstration
    // ------------------------------------------------------------

    /** Simple generic node. */
    static class Node<T> {
        private T value;

        public void setValue(T value) {
            this.value = value;
        }

        public T getValue() {
            return value;
        }
    }

    /** Node that narrows the type to LocalDate. */
    static class DateNode extends Node<java.time.LocalDate> {
        @Override
        public void setValue(java.time.LocalDate value) {
            super.setValue(value);
        }
    }
}
